format = """
 $status $hostname$username$sudo in $directory $git_branch $rust \n
\
"""

[hostname]
ssh_only = false
ssh_symbol = " SSH "
format = '[$ssh_symbol](bold blue)[$hostname](bold green)'
# trim_at = '.companyname.com'
trim_at = ""
disabled = false

[username]
style_user = 'green bold'
style_root = 'black bold'
format = '[@$user]($style)'
disabled = false
show_always = true

[directory]
truncation_length = 8
truncation_symbol = '…/'
format = "[$read_only]($read_only_style)[$path]($style)"
read_only = "[RO]"

[rust]
symbol = "🦀"
format = '[$symbol$version](red bold)'

[git_branch]
symbol = ''
truncation_length = 4
truncation_symbol = ''
# ignore_branches = ['master', 'main']
style = "bold purple"
format = "[$symbol]($style)[$branch(:$remote_branch)]($style)"

[status]
style = ''
symbol = '[ $common_meaning]($bold red)'
success_symbol = ""
format = '[$symbol$signal_name]($style)'
map_symbol = false
disabled = false

[sudo]
style = 'bold red'
format = "[ with sudo]($style)"
disabled = false
