# starship.toml

# format
format = " $hostname$username$sudo in $directory $character"
right_format = "$git_branch $package $status "

# basic settings
add_newline = false

[hostname]
ssh_only = false
ssh_symbol = " SSH "
format = '[$ssh_symbol](bold blue)[$hostname](bold green)'
# trim_at = '.companyname.com'
trim_at = ""
disabled = false

[username]
style_user = 'green bold'
style_root = 'black bold'
format = '[@$user]($style)'
disabled = false
show_always = true

[directory]
truncation_length = 4
truncation_symbol = '…/'
format = "[$read_only]($read_only_style)[$path]($style)"
read_only = "[RO]"

[git_branch]
symbol = ''
truncation_length = 4
truncation_symbol = ''
# ignore_branches = ['master', 'main']
style = "bold purple"
format = "[$symbol]($style)[$branch(:$remote_branch)]($style)"

[status]
style = ''
symbol = '[ $common_meaning]($bold red)'
success_symbol = "[](bold yellow)"
format = '[$symbol$signal_name]($style)'
map_symbol = false
disabled = false

[sudo]
style = 'bold red'
format = "[ with sudo]($style)"
disabled = false

[package]
format = '[$version](208 bold)'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
format = "$symbol "
