name: Format code with stylua
on:
  push:
    branches:
      - "main"
    paths:
      - "nvim/**.lua" # only format lua files
jobs:
  formating_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          # CLI arguments
          # Default configuration in file `root/stylua.toml`
          args: .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format with stylua"
